name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Pull Packages
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ env.REMOTE_ADDR }}
          user: ${{ env.REMOTE_USER }}
          pass: ${{ env.REMOTE_PASSWORD }}
          # scp from local to remote
          scp: from ./cofmgr to ~/cofmgr


