name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Pull Packages
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Swagger Generator
      run: |
        go mod tidy
        go install github.com/swaggo/swag/cmd/swag
        swag init
    
    - name: Deploy
      run: |
        apt update
        apt install -y sshpass
        go build .
        sshpass -p ${{ env.REMOTE_PASSWORD }} scp ./cofmgr ${{ env.REMOTE_USER }}/${{ env.REMOTE_ADDR }}

