name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Pull Packages
      run: go mod tidy

    - name: Build
      run: go build .

    - name: Test
      run: go test -v ./...
    
    - name: Deploy
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        host: ${{ secrets.REMOTE_ADDR }}
        user: ${{ secrets.REMOTE_USER }}
        pass: ${{ secrets.REMOTE_PASSWORD }}
        first_ssh: |
          killall cofmgr-server > /dev/null 2>&1
        # scp from local to remote
        scp: ./cofmgr => ~/auto-deploy/backend/
        last_ssh: |
          cd ~/auto-deploy/backend/
          mv ./cofmgr ./cofmgr-server
          nohup ./cofmgr-server > cofmgr-server.log 2>&1 &


